<?php

namespace Container4YmoSxL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Fx_0PoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Fx.0Po' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Fx.0Po'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligneFraisForfaitRepository' => ['privates', 'App\\Repository\\LigneFraisForfaitRepository', 'getLigneFraisForfaitRepositoryService', true],
        ], [
            'ligneFraisForfaitRepository' => 'App\\Repository\\LigneFraisForfaitRepository',
        ]);
    }
}
