<?php

namespace Container4YmoSxL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFraisForfait2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y77r63N.App\Entity\FraisForfait' shared service.
     *
     * @return \App\Entity\FraisForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.y77r63N": it references class "App\\Entity\\FraisForfait" but no such service exists.');
    }
}
