<?php

namespace Container4YmoSxL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFraisForfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HP5k.Ho.App\Entity\LigneFraisForfait' shared service.
     *
     * @return \App\Entity\LigneFraisForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HP5k.Ho": it references class "App\\Entity\\LigneFraisForfait" but no such service exists.');
    }
}
