<?php

namespace ContainerHII6QSA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y77r63NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y77r63N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y77r63N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fraisForfait' => ['privates', '.errored..service_locator.y77r63N.App\\Entity\\FraisForfait', NULL, 'Cannot autowire service ".service_locator.y77r63N": it references class "App\\Entity\\FraisForfait" but no such service exists.'],
        ], [
            'fraisForfait' => 'App\\Entity\\FraisForfait',
        ]);
    }
}
