<?php

namespace ContainerHII6QSA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TtWN2ZhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TtWN2Zh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TtWN2Zh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ficheFrai' => ['privates', '.errored..service_locator.TtWN2Zh.App\\Entity\\FicheFrais', NULL, 'Cannot autowire service ".service_locator.TtWN2Zh": it references class "App\\Entity\\FicheFrais" but no such service exists.'],
            'ficheFraisRepository' => ['privates', 'App\\Repository\\FicheFraisRepository', 'getFicheFraisRepositoryService', true],
        ], [
            'ficheFrai' => 'App\\Entity\\FicheFrais',
            'ficheFraisRepository' => 'App\\Repository\\FicheFraisRepository',
        ]);
    }
}
