<?php

namespace ContainerHII6QSA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheFraisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TtWN2Zh.App\Entity\FicheFrais' shared service.
     *
     * @return \App\Entity\FicheFrais
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TtWN2Zh": it references class "App\\Entity\\FicheFrais" but no such service exists.');
    }
}
