<?php

namespace ContainerHII6QSA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneFraisHorsForfaitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.93tZoOk.App\Entity\LigneFraisHorsForfait' shared service.
     *
     * @return \App\Entity\LigneFraisHorsForfait
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.93tZoOk": it references class "App\\Entity\\LigneFraisHorsForfait" but no such service exists.');
    }
}
