<?php

namespace ContainerYe8aCUS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FhZDZ7kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fhZDZ7k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fhZDZ7k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etat' => ['privates', '.errored..service_locator.fhZDZ7k.App\\Entity\\Etat', NULL, 'Cannot autowire service ".service_locator.fhZDZ7k": it references class "App\\Entity\\Etat" but no such service exists.'],
        ], [
            'etat' => 'App\\Entity\\Etat',
        ]);
    }
}
