<?php

namespace ContainerYe8aCUS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\VisiteurType' shared autowired service.
     *
     * @return \App\Form\VisiteurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/VisiteurType.php';

        return $container->privates['App\\Form\\VisiteurType'] = new \App\Form\VisiteurType();
    }
}
