<?php

namespace ContainerBzxsNvL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I_BhFTGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i.bhFTG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i.bhFTG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ficheFrai' => ['privates', '.errored..service_locator.i.bhFTG.App\\Entity\\FicheFrais', NULL, 'Cannot autowire service ".service_locator.i.bhFTG": it references class "App\\Entity\\FicheFrais" but no such service exists.'],
        ], [
            'ficheFrai' => 'App\\Entity\\FicheFrais',
        ]);
    }
}
