<?php

namespace ContainerBzxsNvL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fhZDZ7k.App\Entity\Etat' shared service.
     *
     * @return \App\Entity\Etat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fhZDZ7k": it references class "App\\Entity\\Etat" but no such service exists.');
    }
}
