<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzxsNvL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzxsNvL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBzxsNvL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBzxsNvL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBzxsNvL\App_KernelDevDebugContainer([
    'container.build_hash' => 'BzxsNvL',
    'container.build_id' => '4415c3aa',
    'container.build_time' => 1647440518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzxsNvL');
